apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: filemanager-demo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: filemanager-demo
    spec:
      containers:
      - name: filemanager-demo
        image: opuscapita/filemanager-demo:latest
        ports:
        - containerPort: 3020
